---
version: '3'
services:
  artemis:
    platform: linux/amd64
    image: quay.io/artemiscloud/activemq-artemis-broker
    container_name: activemq
    ports:
      - "61616:61616"
      - "5672:5672"
      - "8161:8161"
    environment:
      AMQ_USER: user
      AMQ_PASSWORD: password
      AMQ_EXTRA_ARGS: "--nio --host 0.0.0.0 --http-host 0.0.0.0 --relax-jolokia"
  # nginx:
  #   image: nginx
  #   container_name: nginx-activemq
  #   ports:
  #     - "8161:8161"
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER_NAME=admin
      - USER_PASSWORD=password
      - PASSWORD_ACCESS=true
    ports:
      - 2222:2222
    restart: unless-stopped